# Generated by Django 5.2.3 on 2025-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_administradorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='supplier_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
